### ISSUE TITLE
How to look up all assets currently owned by a user

### ISSUE THREAD

**Issue by Flaise** [bigchaindb/bigchaindb-driver#201]
I'm trying to list all asset IDs or transaction IDs (or however you do it) that currently belong to a particular user. I'm guessing the function I'm looking for is get_owned_ids() from the "bigchaindb" repository but I'm not seeing any documentation of how to use it and I don't see it in this repository. Is there something I'm missing?

**Comment by sohkai** [comment]
@Flaise We're currently working on getting this into the HTTP API and then the driver. Stay tuned!

**Comment by sohkai** [comment]
Hey @Flaise, sorry this took so long!

With https://github.com/bigchaindb/bigchaindb-driver/pull/231 merged, we've finally added this functionality natively into the driver.

If you'd like to give everything a go now, you can use the latest master of both the driver and the server. Otherwise, we'll be cutting a new release next week for both!
