### ISSUE TITLE
ImportError: cannot import name 'Asset'

### ISSUE THREAD

**Issue by jiebanghan** [bigchaindb/bigchaindb-driver#210]
* bigchaindb-driver version: bigchaindb_driver-0.2.0
* Python version: 3.5.2
* Operating System:  Ubuntu 16.04 LTS

### Description

When I installed the bigchaindb driver here, then after I runed python:
from bigchaindb_driver import BigchainDB
bdb = BigchainDB('http://localhost:9984/api/v1')

The console shows ：
  File "/home/zzjs/test.py", line 2, in <module>
    from bigchaindb_driver import BigchainDB
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver-0.2.0.dev0-py3.5.egg/bigchaindb_driver/__init__.py", line 1, in <module>
    from .driver import BigchainDB   # noqa
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver-0.2.0.dev0-py3.5.egg/bigchaindb_driver/driver.py", line 2, in <module>
    from .offchain import prepare_transaction, fulfill_transaction
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver-0.2.0.dev0-py3.5.egg/bigchaindb_driver/offchain.py", line 18, in <module>
    from .utils import (
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver-0.2.0.dev0-py3.5.egg/bigchaindb_driver/utils.py", line 9, in <module>
    from bigchaindb.common.transaction import Asset
ImportError: cannot import name 'Asset'

then I open the transaction.py , I found there is no Asset in it.
What should I do to solve the problem?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by TimDaub** [comment]
Hi,


thanks for checking out the Python driver.
It's master branch is currently not synched with BigchainDB server's master branch.

To fix your problem:

- [Install BigchainDB-driver as outlined here using pip](https://docs.bigchaindb.com/projects/py-driver/en/latest/quickstart.html#quickstart-installation)
- [Install BigchainDB-server as outlined here using pip](https://docs.bigchaindb.com/projects/server/en/latest/quickstart.html)


Tell me if this fixes your problem so that we can close this issue.

**Comment by jiebanghan** [comment]
Thank you for  your response.
When I pip  uninstall bigchaindb_driver.
then I  pip install bigchaindb_driver
It shows:

Successfully built bigchaindb-driver bigchaindb rethinkdb pysha3 cryptoconditions python-rapidjson logstats multipipes pyyaml PyNaCl itsdangerous aniso8601 MarkupSafe pycparser
Installing collected packages: requests, rethinkdb, pysha3, base58, six, pycparser, cffi, PyNaCl, cryptoconditions, statsd, python-rapidjson, logstats, Werkzeug, MarkupSafe, Jinja2, itsdangerous, click, flask, python-dateutil, aniso8601, pytz, flask-restful, gunicorn, multipipes, jsonschema, pyyaml, bigchaindb, bigchaindb-driver
Successfully installed Jinja2-2.8 MarkupSafe-0.23 PyNaCl-1.0.1 Werkzeug-0.11.15 aniso8601-0.92 base58-0.2.2 bigchaindb-0.9.0.dev0 bigchaindb-driver cffi-1.9.1 click-6.7 cryptoconditions-0.5.1 flask-0.12 flask-restful-0.3.5 gunicorn-19.6.0 itsdangerous-0.24 jsonschema-2.5.1 logstats-0.2.1 multipipes-0.1.0 pycparser-2.17 pysha3-1.0.0 python-dateutil python-rapidjson-0.0.8 pytz-2016.10 pyyaml-3.12 requests-2.12.4 rethinkdb-2.3.0.post6 six-1.10.0 statsd-3.2.1
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.



then I  do : from bigchaindb_driver import BigchainDB
the console show me:

 from bigchaindb_driver import BigchainDB
  File "/home/zzjs/.local/lib/python3.5/site-packages/bigchaindb_driver/__init__.py", line 1, in <module>
    from .driver import BigchainDB   # noqa
  File "/home/zzjs/.local/lib/python3.5/site-packages/bigchaindb_driver/driver.py", line 2, in <module>
    from .offchain import prepare_transaction, fulfill_transaction
  File "/home/zzjs/.local/lib/python3.5/site-packages/bigchaindb_driver/offchain.py", line 18, in <module>
    from .utils import (
  File "/home/zzjs/.local/lib/python3.5/site-packages/bigchaindb_driver/utils.py", line 9, in <module>
    from bigchaindb.common.transaction import Asset
ImportError: cannot import name 'Asset'

So what should I do ? Can you help me?  Thank you very much.

**Comment by TimDaub** [comment]
Hi,


it seems like you're still using the latest master branch of the driver for some reason.
`pip uninstall` probably doesn't remove the incompatible version of the driver you've installed in the first place.

I suggest to delete or re-create a virtual environment and install `pip install bigchaindb_driver` again.

Since this seems to be a problem related to your setup I'd recommend that you join our gitter channel and we work it out there. To do so, follow this link: https://gitter.im/bigchaindb/bigchaindb

**Comment by jiebanghan** [comment]
Thank you very much for your help.
