### ISSUE TITLE
ModuleNotFoundError: No module named 'bigchaindb_driver'

### ISSUE THREAD

**Issue by ijazul-haq** [bigchaindb/bigchaindb-driver#346]
* Python version: 3.6.3
* Operating System: Windows 7 Ultimate, 64

### Description

I use Python (Django), i'm trying to install BigchainDB driver and want to use IPDB. 
I run this `pip install bigchaindb` and I guess it executed successfully.
I import bigchaindb_driver like that `from bigchaindb_driver import BigchainDB`. Now when i run the server using `python manage.py runserver` it gives me this error.
**ModuleNotFoundError: No module named 'bigchaindb_driver'**

I have actually these questions:
1. If i want to use IPDB, i still have to install bigchainDB on my local machine?
2. What exactly i need to start a project on bigchainDB, as i have installed MongoDB and RethinkDB but i don't exactly know weather i need them or not.

**Comment by codegeschrei** [comment]
Hey!
The error you have is because you used the wrong package. If you want to use the driver it is the `bigchaindb_driver` package. 
We have some [instructions](https://docs.bigchaindb.com/projects/py-driver/en/latest/quickstart.html) to help you set it up, maybe that already helps with your questions?
