### ISSUE TITLE
transaction status call missing from the latest driver

### ISSUE THREAD

**Issue by agwego** [bigchaindb/bigchaindb-driver#419]
* bigchaindb-driver version: 0.5.0a4
* bigchaindb **server** version (`bigchaindb -v`): branch alpha-3
* Python version: 3.5.2
* Operating System: Ubuntu 16.04.3 LTS

The trnasaction.status call is missing from the driver.

**Comment by vrde** [comment]
Hi @agwego, when you send a transaction to the network, the driver will wait for that transaction to be included in a block (this is true since version `0.5.0a2`). If there is a problem, than the call will raise an exception.

I'll keep this issue open so we remember to be more explicit in the documentation and examples.

**Comment by agwego** [comment]
You're missing the point.

I have code in production against BigchainDB 1.3, I'm in the process of migrating that code to 2.X, I now have to make the decision do I branch my code which is annoying, or work around the issue, because you changed the API and now my code doesn't work with 2.X. This includes Python, Java, Node.js code bases. I've tweaked your codebase quite a bit, because your logging leaves a lot to be desired.

**Comment by codegeschrei** [comment]
Hey @agwego I've opened a PR to show how to check for the status of a transaction. If you're interested you can give some feedback.
